# Generated by Django 4.1.2 on 2022-10-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numticket', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(max_length=50)),
                ('idcliente', models.PositiveIntegerField()),
            ],
        ),
    ]
